---
name: Snapcast Server
version: "0.27.0-r4-v4"
slug: snapserver
panel_icon: mdi:music-circle
description: Snapcast Server is an open-source multi-room audio solution
url: https://github.com/alexyao2015/snapcast-addon
image: ghcr.io/alexyao2015/music-snapserver-addon
init: false
arch:
  - amd64
map:
  - addon_config:rw
host_network: true
